# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from images import icons
from PyQt5 import QtCore, QtGui, QtWidgets
import webbrowser
from  ButtonControl import  ButtonControl


class UiMainwindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 500)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 600, 500))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setStyleSheet("QWidget{\n"
                                  "background:qlineargradient(spread:pad, x1:0.506, y1:1, x2:0.511273, y2:0, stop:0 rgba(104, 104, 104, 255), stop:1 rgba(198, 198, 198, 255))\n"
                                  "}\n"
                                  "QPushButton{\n"
                                  "border:3px solid black;\n"
                                  "border-radius:17px;\n"
                                  "background:none;\n"
                                  "}\n"
                                  "QPushButton:hover{\n"
                                  "background-color:rgba(155, 155, 155, 150);\n"
                                  "}\n"
                                  "QPushButton:pressed{\n"
                                  "background-color:rgb(182, 182, 182, 150);\n"
                                  "}\n"
                                  "QFrame{\n"
                                  "background:none;\n"
                                  "}")
        self.page_1.setObjectName("page_1")
        self.pushButton_sound = QtWidgets.QPushButton(self.page_1)
        self.pushButton_sound.setGeometry(QtCore.QRect(70, 440, 51, 51))
        self.pushButton_sound.setAutoFillBackground(False)
        self.pushButton_sound.setStyleSheet("")
        self.pushButton_sound.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_sound.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/energy-clipart-sound-12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sound.setIcon(icon)
        self.pushButton_sound.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_sound.setCheckable(False)
        self.pushButton_sound.setChecked(False)
        self.pushButton_sound.setAutoRepeat(False)
        self.pushButton_sound.setAutoExclusive(False)
        self.pushButton_sound.setDefault(False)
        self.pushButton_sound.setFlat(False)
        self.pushButton_sound.setObjectName("pushButton_sound")
        self.pushButton_settings = QtWidgets.QPushButton(self.page_1)
        self.pushButton_settings.setGeometry(QtCore.QRect(10, 440, 51, 51))
        self.pushButton_settings.setAutoFillBackground(False)
        self.pushButton_settings.setStyleSheet("")
        self.pushButton_settings.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_settings.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/gear2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_settings.setIcon(icon1)
        self.pushButton_settings.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_settings.setCheckable(False)
        self.pushButton_settings.setChecked(False)
        self.pushButton_settings.setAutoRepeat(False)
        self.pushButton_settings.setAutoExclusive(False)
        self.pushButton_settings.setDefault(False)
        self.pushButton_settings.setFlat(False)
        self.pushButton_settings.setObjectName("pushButton_settings")
        self.pushButton_generate_password = QtWidgets.QPushButton(self.page_1)
        self.pushButton_generate_password.setGeometry(QtCore.QRect(200, 430, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_generate_password.setFont(font)
        self.pushButton_generate_password.setStyleSheet("QPushButton{\n"
                                                        "border:3px solid black;\n"
                                                        "border-radius:17px;\n"
                                                        "}\n"
                                                        "QPushButton:hover{\n"
                                                        "background-color:rgba(155, 155, 155, 150);\n"
                                                        "}\n"
                                                        "QPushButton:pressed{\n"
                                                        "background-color:rgb(178, 178, 178, 150);\n"
                                                        "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/bird.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_generate_password.setIcon(icon2)
        self.pushButton_generate_password.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_generate_password.setObjectName("pushButton_generate_password")
        self.label_by_denchik = QtWidgets.QLabel(self.page_1)
        self.label_by_denchik.setGeometry(QtCore.QRect(440, 470, 145, 13))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_by_denchik.setFont(font)
        self.label_by_denchik.setStyleSheet("background:none;\n"
                                            "\n"
                                            "\n"
                                            "\n"
                                            "QComboBox{\n"
                                            "background:rgb(148, 148, 148);\n"
                                            "color:white;\n"
                                            "border:3px solid black;\n"
                                            "}\n"
                                            "QComboBox:focus{\n"
                                            "border:3px solid rgb(110, 86, 227);\n"
                                            "}")
        self.label_by_denchik.setObjectName("label_by_denchik")
        self.frameSettings = QtWidgets.QFrame(self.page_1)
        self.frameSettings.setGeometry(QtCore.QRect(40, 30, 491, 351))
        self.frameSettings.setStyleSheet("QCheckBox {\n"
                                         "    spacing: 5px;\n"
                                         "    background:none;\n"
                                         "}\n"
                                         "QCheckBox:hover{\n"
                                         "background:rgba(171, 171, 171, 120);\n"
                                         "border-radius:5px;\n"
                                         "}\n"
                                         "\n"
                                         "QCheckBox::indicator {\n"
                                         "    width: 17px;\n"
                                         "    height: 17px;\n"
                                         "}\n"
                                         "\n"
                                         "QCheckBox::indicator:unchecked {\n"
                                         "    image:url(:/images/unchecked.png)\n"
                                         "}\n"
                                         "\n"
                                         "\n"
                                         "QCheckBox::indicator:unchecked:pressed {\n"
                                         "       width:15px;\n"
                                         "    height:15px;;\n"
                                         "}\n"
                                         "\n"
                                         "QCheckBox::indicator:checked {\n"
                                         "    image:url(:/images/checked.png);\n"
                                         "}\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "QCheckBox::indicator:checked:pressed {\n"
                                         "   width:15px;\n"
                                         "    height:15px;\n"
                                         "}\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "")
        self.frameSettings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSettings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSettings.setObjectName("frameSettings")
        self.label_lens_password_str = QtWidgets.QLabel(self.frameSettings)
        self.label_lens_password_str.setGeometry(QtCore.QRect(10, 30, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_lens_password_str.setFont(font)
        self.label_lens_password_str.setObjectName("label_lens_password_str")
        self.frame_slider = QtWidgets.QFrame(self.frameSettings)
        self.frame_slider.setGeometry(QtCore.QRect(90, 10, 171, 61))
        self.frame_slider.setStyleSheet("QSlider{\n"
                                        "background:none;\n"
                                        "}")
        self.frame_slider.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_slider.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_slider.setObjectName("frame_slider")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_slider)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 35, 151, 22))
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
                                            "    border: 1px solid rgb(146, 146, 146);\n"
                                            "    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                            "    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(90, 90, 90, 255), stop:1 rgba(239, 239, 239, 255));\n"
                                            "    margin: 2px 0;\n"
                                            "}\n"
                                            "\n"
                                            "QSlider::handle:horizontal {\n"
                                            "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                                            "    border: 1px solid #5c5c5c;\n"
                                            "    width: 18px;\n"
                                            "    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                            "    border-radius: 3px;}")
        self.horizontalSlider.setMinimum(4)
        self.horizontalSlider.setMaximum(20)
        self.horizontalSlider.setProperty("value", 10)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_lens_password_int = QtWidgets.QLabel(self.frame_slider)
        self.label_lens_password_int.setGeometry(QtCore.QRect(70, 0, 26, 29))
        self.label_lens_password_int.setObjectName("label_lens_password_int")
        self.line = QtWidgets.QFrame(self.frameSettings)
        self.line.setGeometry(QtCore.QRect(0, 70, 491, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_language = QtWidgets.QLabel(self.frameSettings)
        self.label_language.setGeometry(QtCore.QRect(10, 100, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_language.setFont(font)
        self.label_language.setObjectName("label_language")
        self.comboBox_language = QtWidgets.QComboBox(self.frameSettings)
        self.comboBox_language.setGeometry(QtCore.QRect(90, 100, 171, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.comboBox_language.setFont(font)
        self.comboBox_language.setStyleSheet("QComboBox {\n"
                                             "    border: 1px solid gray;\n"
                                             "    border-radius: 3px;\n"
                                             "    padding: 1px 18px 1px 3px;\n"
                                             "    min-width: 6em;\n"
                                             "    border-radius:6px;\n"
                                             "}\n"
                                             "\n"
                                             "QComboBox:editable {\n"
                                             "    background: white;\n"
                                             "}\n"
                                             "\n"
                                             "QComboBox:!editable, QComboBox::drop-down:editable {\n"
                                             "     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                             "                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
                                             "                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
                                             "}\n"
                                             "\n"
                                             "/* QComboBox gets the \"on\" state when the popup is open */\n"
                                             "QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
                                             "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                             "                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
                                             "                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
                                             "}\n"
                                             "\n"
                                             "QComboBox:on { /* shift the text when the popup opens */\n"
                                             "    padding-top: 3px;\n"
                                             "    padding-left: 4px;\n"
                                             "}\n"
                                             "\n"
                                             "QComboBox::drop-down {\n"
                                             "    subcontrol-origin: padding;\n"
                                             "    subcontrol-position: top right;\n"
                                             "    width: 15px;\n"
                                             "\n"
                                             "    border-left-width: 1px;\n"
                                             "    border-left-color: darkgray;\n"
                                             "    border-left-style: solid; /* just a single line */\n"
                                             "    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
                                             "    border-bottom-right-radius: 3px;\n"
                                             "}\n"
                                             "\n"
                                             "QComboBox::down-arrow {\n"
                                             "image:url(:/images/gear.png);\n"
                                             "height:15px;\n"
                                             "\n"
                                             "    \n"
                                             "}\n"
                                             "\n"
                                             "QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
                                             "    top: 0px;\n"
                                             "    left: 0px;\n"
                                             "}")
        self.comboBox_language.setEditable(False)
        self.comboBox_language.setDuplicatesEnabled(False)
        self.comboBox_language.setObjectName("comboBox_language")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/english_flag.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_language.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/Russian_flag.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_language.addItem(icon4, "")
        self.line_2 = QtWidgets.QFrame(self.frameSettings)
        self.line_2.setGeometry(QtCore.QRect(0, 130, 491, 16))
        self.line_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_2.setMouseTracking(False)
        self.line_2.setAcceptDrops(False)
        self.line_2.setAutoFillBackground(False)
        self.line_2.setStyleSheet("QLine{\n"
                                  "background:red;\n"
                                  "}")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.checkBox_spec_symbols = QtWidgets.QCheckBox(self.frameSettings)
        self.checkBox_spec_symbols.setGeometry(QtCore.QRect(20, 170, 94, 17))
        self.checkBox_spec_symbols.setObjectName("checkBox_spec_symbols")
        self.checkBox_numbers = QtWidgets.QCheckBox(self.frameSettings)
        self.checkBox_numbers.setGeometry(QtCore.QRect(20, 190, 58, 17))
        self.checkBox_numbers.setCheckable(True)
        self.checkBox_numbers.setChecked(True)
        self.checkBox_numbers.setObjectName("checkBox_numbers")
        self.label_use = QtWidgets.QLabel(self.frameSettings)
        self.label_use.setGeometry(QtCore.QRect(10, 150, 81, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_use.setFont(font)
        self.label_use.setObjectName("label_use")
        self.checkBox_save_in_database = QtWidgets.QCheckBox(self.frameSettings)
        self.checkBox_save_in_database.setGeometry(QtCore.QRect(330, 330, 155, 17))
        self.checkBox_save_in_database.setChecked(True)
        self.checkBox_save_in_database.setObjectName("checkBox_save_in_database")
        self.frame_slider.raise_()
        self.label_lens_password_str.raise_()
        self.line.raise_()
        self.label_language.raise_()
        self.comboBox_language.raise_()
        self.line_2.raise_()
        self.checkBox_spec_symbols.raise_()
        self.checkBox_numbers.raise_()
        self.label_use.raise_()
        self.checkBox_save_in_database.raise_()
        self.pushButton_legend = QtWidgets.QPushButton(self.page_1)
        self.pushButton_legend.setGeometry(QtCore.QRect(540, 10, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_legend.setFont(font)
        self.pushButton_legend.setStyleSheet("QPushButton{\n"
                                             "border: 2px solid rgb(110, 86, 227);\n"
                                             "border-radius:10px;\n"
                                             "background:none;\n"
                                             "}\n"
                                             "QPushButton:hover{\n"
                                             "border:2px solid red;\n"
                                             "background:black;\n"
                                             "color:red;\n"
                                             "}\n"
                                             "QPushButton:pressed{\n"
                                             "color:black;\n"
                                             "}")
        self.pushButton_legend.setObjectName("pushButton_legend")
        self.dial_volume = QtWidgets.QDial(self.page_1)
        self.dial_volume.setGeometry(QtCore.QRect(125, 434, 61, 61))
        self.dial_volume.setStyleSheet("QDial{\n"
                                       "background:black;\n"
                                       "}")
        self.dial_volume.setProperty("value", 50)
        self.dial_volume.setOrientation(QtCore.Qt.Horizontal)
        self.dial_volume.setWrapping(False)
        self.dial_volume.setNotchesVisible(False)
        self.dial_volume.setObjectName("dial_volume")
        self.label_volume = QtWidgets.QLabel(self.page_1)
        self.label_volume.setGeometry(QtCore.QRect(130, 420, 54, 19))
        self.label_volume.setObjectName("label_volume")
        self.pushButton_next = QtWidgets.QPushButton(self.page_1)
        self.pushButton_next.setGeometry(QtCore.QRect(60, 390, 41, 41))
        self.pushButton_next.setStyleSheet("")
        self.pushButton_next.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next.setIcon(icon5)
        self.pushButton_next.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_back_music = QtWidgets.QPushButton(self.page_1)
        self.pushButton_back_music.setGeometry(QtCore.QRect(10, 390, 41, 41))
        self.pushButton_back_music.setStyleSheet("")
        self.pushButton_back_music.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_back_music.setIcon(icon6)
        self.pushButton_back_music.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_back_music.setObjectName("pushButton_back_music")
        self.frame_ramka = QtWidgets.QFrame(self.page_1)
        self.frame_ramka.setGeometry(QtCore.QRect(40, 30, 491, 351))
        self.frame_ramka.setStyleSheet("QFrame{\n"
                                       "border:3px solid black;\n"
                                       "border-radius:15px;\n"
                                       "background:none;\n"
                                       "}")
        self.frame_ramka.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ramka.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ramka.setObjectName("frame_ramka")
        self.frame_ramka.raise_()
        self.pushButton_sound.raise_()
        self.pushButton_settings.raise_()
        self.pushButton_generate_password.raise_()
        self.label_by_denchik.raise_()
        self.frameSettings.raise_()
        self.pushButton_legend.raise_()
        self.dial_volume.raise_()
        self.label_volume.raise_()
        self.pushButton_next.raise_()
        self.pushButton_back_music.raise_()
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("QWidget{\n"
                                  "background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(153, 153, 153, 255), stop:1 rgba(108, 108, 108, 255));\n"
                                  "}")
        self.page_2.setObjectName("page_2")
        self.progress_bar = QtWidgets.QProgressBar(self.page_2)
        self.progress_bar.setGeometry(QtCore.QRect(130, 280, 351, 41))
        self.progress_bar.setProperty("value", 50)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setObjectName("progress_bar")
        self.label_loading = QtWidgets.QLabel(self.page_2)
        self.label_loading.setGeometry(QtCore.QRect(210, 200, 201, 61))
        self.label_loading.setStyleSheet("background:none;")
        self.label_loading.setObjectName("label_loading")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("QWidget{\n"
                                  "background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(153, 153, 153, 255), stop:1 rgba(108, 108, 108, 255));\n"
                                  "}\n"
                                  "QPushButton{\n"
                                  "background:none;\n"
                                  "border:2\n"
                                  "}\n"
                                  "QPushButton{\n"
                                  "border:3px solid black;\n"
                                  "border-radius:17px;\n"
                                  "background:none;\n"
                                  "}\n"
                                  "QPushButton:hover{\n"
                                  "background-color:rgba(155, 155, 155, 150);\n"
                                  "}\n"
                                  "QPushButton:pressed{\n"
                                  "background-color:rgb(182, 182, 182, 150);\n"
                                  "}")
        self.page_3.setObjectName("page_3")
        self.label_password = QtWidgets.QLabel(self.page_3)
        self.label_password.setGeometry(QtCore.QRect(260, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_password.setFont(font)
        self.label_password.setStyleSheet("QLabel{\n"
                                          "background:none;\n"
                                          "}")
        self.label_password.setObjectName("label_password")
        self.pushButton_back_page = QtWidgets.QPushButton(self.page_3)
        self.pushButton_back_page.setGeometry(QtCore.QRect(534, 442, 51, 41))
        self.pushButton_back_page.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/backup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_back_page.setIcon(icon7)
        self.pushButton_back_page.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_back_page.setObjectName("pushButton_back_page")
        self.password = QtWidgets.QLabel(self.page_3)
        self.password.setGeometry(QtCore.QRect(200, 180, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setStyleSheet("QLabel{;\n"
                                    "border:1px solid black;\n"
                                    "border-radius:6px;\n"
                                    "}")
        self.password.setObjectName("password")
        self.pushButton_copy = QtWidgets.QPushButton(self.page_3)
        self.pushButton_copy.setGeometry(QtCore.QRect(170, 270, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.pushButton_copy.setFont(font)
        self.pushButton_copy.setObjectName("pushButton_copy")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBox_language.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def add_function(self):
        """Функции кнопок"""
        self.pushButton_legend.clicked.connect(lambda: webbrowser.open(r'https://goo.su/Gv1QUz'))
        self.horizontalSlider.valueChanged.connect(lambda: )

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_generate_password.setText(_translate("MainWindow", "Сгенерировать"))
        self.label_by_denchik.setText(_translate("MainWindow", "PasswordGenerator by Den4ik"))
        self.label_lens_password_str.setText(_translate("MainWindow", "Длина пароля:"))
        self.label_lens_password_int.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">15</span></p></body></html>"))
        self.label_language.setText(_translate("MainWindow", "Язык:"))
        self.comboBox_language.setItemText(0, _translate("MainWindow", "English "))
        self.comboBox_language.setItemText(1, _translate("MainWindow", "Russian"))
        self.checkBox_spec_symbols.setText(_translate("MainWindow", "Спец символы"))
        self.checkBox_numbers.setText(_translate("MainWindow", "Цифры"))
        self.label_use.setText(_translate("MainWindow", "Использовать:"))
        self.checkBox_save_in_database.setText(_translate("MainWindow", "Сохранить в базе данных"))
        self.pushButton_legend.setText(_translate("MainWindow", "Легенда"))
        self.label_volume.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Volume</span></p></body></html>"))
        self.progress_bar.setFormat(_translate("MainWindow", "%p%"))
        self.label_loading.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">Загрузка...</span></p></body></html>"))
        self.label_password.setText(_translate("MainWindow", "Пароль:"))
        self.password.setText(_translate("MainWindow", "4234213423"))
        self.pushButton_copy.setText(_translate("MainWindow", "Скопировать"))


